[package]
name = "multidid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
iri-string = { version = "0.6", features = ["serde"] }
unsigned-varint = { version = "0.7", features = ["std"] }
thiserror = "1"
