[package]
name = "varsig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unsigned-varint = { version = "0.7", features = ["std"] }
thiserror = "1"
