name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout cacao-rs
      uses: actions/checkout@v2

    - name: Cache Cargo registry and build artifacts
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Test
      run: cargo test

    - name: Fmt
      run: cargo fmt -- --check

    - name: Clippy
      run: RUSTFLAGS="-Dwarnings" cargo clippy
